const fs = require('fs');

const d = {
  "rattata-alola": "O ambiente noturno alterou seu ciclo biológico. Ele procura sobras de comida nas lixeiras urbanas.",
  "raticate-alola": "Suas bochechas estocam grandes porções de grãos. Ele comanda pequenos grupos na busca por alimentos.",
  "raichu-alola": "Sua dieta ativou instintos mentais até então ocultos. Ele utiliza sua cauda achatada para planar longas distâncias.",
  "meowth-galar": "Os ventos oceânicos enrijeceram completamente os seus pelos. A moeda frontal tornou-se uma chapa de aço impenetrável.",
  "farfetchd-galar": "O pesado talo colhido fortaleceu suas patas inferiores. Ele caminha com passos rígidos em direção ao inimigo.",
  "mister-mime-galar": "A umidade retida congela o tapete sob os seus pés. Ele produz barreiras através do sapateado ininterrupto.",
  "corsola-galar": "Alterações de temperatura erradicaram o antigo recife local. Seus galhos ocos sugam discretamente a vitalidade de nadadores.",
  "zigzagoon-galar": "Observações apontam que esta forma é a origem inalterada da espécie. Ele ziguezagueia provocando acidentes nos prados rurais.",
  "linoone-galar": "As unhas compridas favorecem estocadas diretas e mortíferas. Ele embosca pequenas caças correndo estritamente em linha reta.",
  "darumaka-galar": "O rigoroso inverno hibernou seu estômago inflamável. Ele mastiga montinhos de gelo para esfriar seu pulso basal.",
  "darmanitan-zen": "Pancadas diretas forçam a criatura a adotar uma postura defensiva letárgica. Ele repousa imóvel como entulho até cicatrizar os ferimentos.",
  "darmanitan-galar-standard": "O domo esférico na cabeça inibe parte de sua hostilidade matinal. Ele armazena alimento fresco debaixo deste aglomerado nevoso.",
  "darmanitan-galar-zen": "O aumento térmico na fúria derrete sua proteção gélida parcialmente. Ele lança chamas vivas pelas partes expostas temporariamente.",
  "yamask-galar": "Uma alvenaria arruinada aderiu aos resquícios de espírito do lugar. Aqueles que tocam os entalhes sentem breves memórias tristes cruzarem a mente.",
  "stunfisk-galar": "A saturação aquática oxidou sua epiderme enegrecida. Ele descansa nas poças se camuflando feito uma perigosa armadilha esquecida.",
  "voltorb-hisui": "A estrutura de base tem raízes num vegetal maciço esculpido pela natureza. Ele despeja estática pelo orifício oco ao notar barulhos acentuados.",
  "electrode-hisui": "As correntes excessivas queimaram sua folhagem interior formando carvão. Ele vomita parte desta tensão para não causar autocombustão nas florestas.",
  "qwilfish-hisui": "As correntes polares concentraram doses altíssimas do seu lodo interior orgânico. Ele caça algas absorvendo minerais cruciais nos fiordes remotos.",
  "sneasel-hisui": "As presas ungueais pontiagudas possuem dutos paralisantes roxos. Ele pendura seu peso nos paredões da cordilheira nevosa em rotinas de escalada.",
  "lilligant-hisui": "O terreno íngreme do norte inflou de imediato suas musculaturas da coxa longa. Ela salta ladeiras completas para fugir de investidas diretas iminentes.",
  "basculin-blue-striped": "O isolamento em baías lodosas apaziguou grande parte dos seus instintos agressores. Costuma nadar em calmos cardumes paralelos à encosta urbanizada.",
  "basculin-white-striped": "O convívio polar reforçou a glicose do pâncreas para aquecimento corpóreo extra. Prioriza preservar oxigênio em vez de iniciar batalhas inúteis na neve.",
  "zorua-hisui": "A inanição invernal o condenou a vaguear na forma de um reflexo de energia psíquica. Ele materializa dores sentidas projetando ilusões ao redor da sua juba acinzentada.",
  "braviary-hisui": "A necessidade de áreas solitárias o levou a planar nos céus rarefeitos glaciais. Emite fortes gritos sônicos impulsionados pelo topete peculiar flamejante psíquico frontal.",
  "sliggoo-hisui": "Sua substância mole adaptou-se a minérios da nascente, enrijecendo em carapaça opaca chumbo. Ele utiliza táticas passivas encolhendo-se e isolando a parte exposta nos combates.",
  "goodra-hisui": "A aversão a extremos climáticos forçou-o para fundos lamacentos dentro do caracol rígido de liga estéril. Costuma escorrer choros ininterruptos ao permanecer longos períodos fisicamente isolado no matagal.",
  "avalugg-hisui": "A base gélida fundiu-se a rochedos de montanhas alpinas pontiagudos. O maxilar esfarela calotas inteiras impulsionadas em lentas arrancadas retas rústicas limpas.",
  "tauros-paldea-combat-breed": "A região favoreceu perus escuros e pescoço fortalecido nesta linhagem agressiva particular. Realiza investidas corpóreas que visam simplesmente desequilibrar o seu nocauteador com impacto brusco contuso frontal.",
  "tauros-paldea-blaze-breed": "O fluxo termal interno é expulso pelo atrito direto entre os pequenos chifres afiados inflamados acalorados encarnados vermelhos fortes duros rubros...",
  "__ignore__": "Word salad occurred"
};
